const USERSTATUSES = {
  BLOCKED: "BLOCKED",
  ACTIVE: "ACTIVE",
};

const TRANSACTIONSTATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  REVERSED: "REVERSED",
};



const ADDRESSSTATUS = {
  ACTIVE: "ACTIVE",
  DELETED: "DELETED",
};

const MESSAGESTATUS = {
  PENDING: "PENDING",
  DELIVERED: "DELIVERED",
  VIEWED: "VIEWED",
  DELETED: "DELETED",
};

const CURRENCYTYPE = {
  NGN: "NGN",
  USD: "USD",
};

const OTPSTATUS = {
  ACTIVE: "ACTIVE",
  USED: "USED",
  EXPIRED: "EXPIRED",
};

const MESSAGES = {
  STATUS500: "An error occured. Please try again or contact customer service",
  TOKENEXPIRED: "Unauthorized. Session timeout",
  INVALIDTOKEN: "An error occurred. Invalid token format",
};

const CALLSTATUS = {
  STARTED: "STARTED",
  ENDED: "ENDED",
  PENDING: "PENDING",
};

const PARTICIPANTSTATUS = {
  ONHOLD: "ONHOLD",
  JOINED: "JOINED",
  LEFT: "LEFT",
  REJECTED: "REJECTED",
  MISSED: "MISSED",
  AWAITING: "AWAITING",
};

const CALLTYPE = {
  SINGLE: "SINGLE",
  GROUP: "GROUP",
};

const MESSAGETYPE = {
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  LOCATION: "LOCATION",
  CALL: "CALL",
  VIDEO: "VIDEO",
  TRANSFER: "TRANSFER",
  AUDIO: "AUDIO",
};

const NOTIFICATIONSTATUS = {
  READ: "READ",
  PENDING: "PENDING",
};

const OTPTYPE = {
  SIGNUP: "SIGNUP",
  UPDATEPROFILE: "UPDATEPROFILE",
  RESETPASSWORD: "RESETPASSWORD",
};

const TRANSACTIONTYPE = {
  AIRTIME: "AIRTIME",
  TRANSFER: "TRANSFER",
  DATA: "DATA",
  UTILITY: "UTILITY",
  TELEVISION: "TELEVISION",
  INTERNET: "INTERNET",
};

const BILLCATEGORY = {
  AIRTIME: "AIRTIME",
  DATA: "DATA",
  TELEVISION: "TELEVISION",
  UTILITY: "UTILITY",
  INTERNET: "INTERNET",
};


const LOCKSTATUS = { LOCKED: "LOCKED", UNLOCKED: "UNLOCKED" };

export {
  USERSTATUSES,
  MESSAGES,
  TRANSACTIONSTATUS,
  MESSAGESTATUS,
  OTPSTATUS,
  CURRENCYTYPE,
  CALLSTATUS,
  CALLTYPE,
  PARTICIPANTSTATUS,
  MESSAGETYPE,
  NOTIFICATIONSTATUS,
  ADDRESSSTATUS,
  OTPTYPE,
  TRANSFERSTATUS,
  TRANSACTIONTYPE,
  BILLCATEGORY,
  BILLIMAGES,
  LOCKSTATUS,
};
